version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aqueduct
permissions:
  - object: /home/ec2-user/aqueduct
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - directory
  - object: /home/ec2-user/aqueduct
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_app.sh
      timeout: 3600
      runas: ec2-user
