trigger:
  - master
pr:
  branches:
    include:
      - '*'
jobs:
  - job: 'test_airflow'
    pool:
      vmImage: 'Ubuntu-16.04'
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
      - bash: pip install -r airflow-requirements.txt
        displayName: Install airflow requirements
      - bash: pip install -r requirements.txt
        displayName: Install custom requirements
      - bash: |
          set -e
          airflow initdb
          for dagfile in `grep -lr --include=*.py "airflow.*DAG" dags/`
          do
            echo "Testing DAG $dagfile"
            python $dagfile
          done
        displayName: Testing DAG integrity
      - bash: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
        displayName: Run lint and formatting checks
