trigger:
  - master
jobs:
  - job: 'test_airflow'
    pool:
      vmImage: 'Ubuntu-16.04'
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
      - bash: pip install -r airflow-requirements.txt
        displayName: Install airflow requirements
      - bash: pip install -r requirements.txt
        displayName: Install custom requirements
      - bash: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
        displayName: Run lint and formatting checks
