postgresql:
  port: 5432
  host: localhost
  user: root
  pass: pass
  db: db
provider:
    lime:
        trips: https://lime.bike/api/partners/v1/mds/los_angeles/trips
        status_updates: https://lime.bike/api/partners/v1/mds/los_angeles/status_changes
        auth: Bearer token
        