name: Build and push Docker images
on:
  push:
    branches:
      - master

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'build+push'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cityofla/ita-data-civis-lab
          tag_with_sha: true
          path: "civis"
          tags: latest
